/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PROJECT;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jberdugo
 */
public class INTERFAZ extends javax.swing.JFrame {

    public static int i = 0;
    public static pokemon p = null;
    static pokemon vectorP[] = new pokemon[6];
    public static ArrayList<pokemon> pokebola = new ArrayList();
    public static boolean sw = false;

    public static void main(String[] args) {
        new INTERFAZ().setVisible(true);

    }

    /**
     * Creates new form INTERFAZ
     */
    public void guardarpk(String name, int power, String tipo) {
        p = new pokemon(power, tipo, name);
        vectorP[i] = p;

        i++;

    }

    public INTERFAZ() {
        initComponents();
        this.setLocationRelativeTo(null);
        //JPANEL_FONDO.setBounds(10,10,90,90);
        // setImageLabel(label_11, "src/IMG/poke3.png");
        // setImageLabel(label_22, "src/IMG/poke1.png");
        setImageLabel(lbl1, "src/IMG/c.PNG");
        setImageLabel(lbl2, "src/IMG/d.PNG");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        JPANEL_FONDO = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        label_11 = new javax.swing.JLabel();
        label_21 = new javax.swing.JLabel();
        label_31 = new javax.swing.JLabel();
        label_61 = new javax.swing.JLabel();
        label_41 = new javax.swing.JLabel();
        label_51 = new javax.swing.JLabel();
        label_12 = new javax.swing.JLabel();
        label_22 = new javax.swing.JLabel();
        label_32 = new javax.swing.JLabel();
        label_42 = new javax.swing.JLabel();
        label_52 = new javax.swing.JLabel();
        label_62 = new javax.swing.JLabel();
        label_43 = new javax.swing.JLabel();
        label_23 = new javax.swing.JLabel();
        label_63 = new javax.swing.JLabel();
        label_13 = new javax.swing.JLabel();
        label_53 = new javax.swing.JLabel();
        label_33 = new javax.swing.JLabel();
        label_44 = new javax.swing.JLabel();
        label_14 = new javax.swing.JLabel();
        label_54 = new javax.swing.JLabel();
        label_34 = new javax.swing.JLabel();
        label_24 = new javax.swing.JLabel();
        label_64 = new javax.swing.JLabel();
        label_45 = new javax.swing.JLabel();
        label_15 = new javax.swing.JLabel();
        label_55 = new javax.swing.JLabel();
        label_35 = new javax.swing.JLabel();
        label_25 = new javax.swing.JLabel();
        label_65 = new javax.swing.JLabel();
        label_46 = new javax.swing.JLabel();
        label_16 = new javax.swing.JLabel();
        label_56 = new javax.swing.JLabel();
        label_36 = new javax.swing.JLabel();
        label_26 = new javax.swing.JLabel();
        label_66 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        mostrar_vectorP = new javax.swing.JButton();
        btn_mostrarcampo = new javax.swing.JButton();
        btn_posicionarjugador = new javax.swing.JButton();
        btn_crear_pokemon = new javax.swing.JButton();
        btn_agarrar = new javax.swing.JButton();
        btn_mostrarpokebolsa = new javax.swing.JButton();
        btn_reiniciar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JUEGO DE POKEMONES");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 0));
        jLabel1.setText("Poké - PUJ");

        JPANEL_FONDO.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(102, 204, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("1");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("3");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("2");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("6");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("1");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("4");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("5");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(415, Short.MAX_VALUE)))
        );

        label_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_11.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_21.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_31.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_61.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_41.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_51.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_12.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_22.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_32.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_42.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_52.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_62.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_43.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_23.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_63.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_13.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_53.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_33.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_44.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_14.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_54.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_34.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_24.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_64.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_45.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_15.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_55.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_35.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_25.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_65.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_46.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_16.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_56.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_36.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_26.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        label_66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_66.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout JPANEL_FONDOLayout = new javax.swing.GroupLayout(JPANEL_FONDO);
        JPANEL_FONDO.setLayout(JPANEL_FONDOLayout);
        JPANEL_FONDOLayout.setHorizontalGroup(
            JPANEL_FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPANEL_FONDOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPANEL_FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPANEL_FONDOLayout.createSequentialGroup()
                        .addGroup(JPANEL_FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_41, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_51, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_61, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPANEL_FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_42, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_52, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_62, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPANEL_FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_33, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_43, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_53, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_63, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPANEL_FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_34, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_44, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_54, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_64, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPANEL_FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_35, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_45, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_55, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_65, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPANEL_FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_36, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_46, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_56, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_66, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(236, 236, 236))
        );
        JPANEL_FONDOLayout.setVerticalGroup(
            JPANEL_FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPANEL_FONDOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(JPANEL_FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPANEL_FONDOLayout.createSequentialGroup()
                        .addGroup(JPANEL_FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPANEL_FONDOLayout.createSequentialGroup()
                                .addComponent(label_12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_32, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_42, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_52, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_62, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPANEL_FONDOLayout.createSequentialGroup()
                                .addComponent(label_11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_31, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_41, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_51, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_61, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPANEL_FONDOLayout.createSequentialGroup()
                                .addComponent(label_13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_23, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_33, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_43, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_53, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_63, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPANEL_FONDOLayout.createSequentialGroup()
                                .addComponent(label_14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_24, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_34, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_44, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_54, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_64, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPANEL_FONDOLayout.createSequentialGroup()
                                .addComponent(label_15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_25, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_35, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_45, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_55, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_65, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPANEL_FONDOLayout.createSequentialGroup()
                                .addComponent(label_16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_26, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_36, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_46, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_56, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_66, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        mostrar_vectorP.setText("MOSTRAR POKEMONES");
        mostrar_vectorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar_vectorPActionPerformed(evt);
            }
        });

        btn_mostrarcampo.setText("MOSTRAR CAMPO");
        btn_mostrarcampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarcampoActionPerformed(evt);
            }
        });

        btn_posicionarjugador.setText("POSICIONAR JUGADOR");
        btn_posicionarjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_posicionarjugadorActionPerformed(evt);
            }
        });

        btn_crear_pokemon.setText("CREAR POKEMON");
        btn_crear_pokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_pokemonActionPerformed(evt);
            }
        });

        btn_agarrar.setText("CAPTURAR POKEMON");
        btn_agarrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agarrarActionPerformed(evt);
            }
        });

        btn_mostrarpokebolsa.setText("MOSTRAR POKEBOLSA");
        btn_mostrarpokebolsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarpokebolsaActionPerformed(evt);
            }
        });

        btn_reiniciar.setText("REINICIAR JUEGO");
        btn_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reiniciarActionPerformed(evt);
            }
        });

        btn_salir.setText("SALIR DEL JUEGO");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPANEL_FONDO, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_mostrarcampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostrar_vectorP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_posicionarjugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_crear_pokemon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_agarrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_mostrarpokebolsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(mostrar_vectorP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_mostrarcampo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_posicionarjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_crear_pokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_agarrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_mostrarpokebolsa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPANEL_FONDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrar_vectorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_vectorPActionPerformed
        if (i == 0) {
            JOptionPane.showMessageDialog(null, "¡NO HAY POKEMONES PARA MOSTRAR!");
        } else if (sw == false) {
            int a = 0;
            // setImageLabel(label_27, "src/IMG/DEFAULT.png");
            // setImageLabel(label_68, "src/IMG/poke3.png");
            for (a = 0; a < i; a++) {
                JOptionPane.showMessageDialog(null, vectorP[a].toString());
            }

        }


    }//GEN-LAST:event_mostrar_vectorPActionPerformed

    private void btn_mostrarcampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarcampoActionPerformed
        //JLabel[] etiqueta = new JLabel[5];
        if (i == 0) {
            JOptionPane.showMessageDialog(null, "NO HAY POKEMONES PARA MOSTRAR. ", "LO SENTIMOS",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            String ruta2 = "src/IMG/DEFAULT.PNG";
            for (int j = 0; j < i; j++) {
                String fi = vectorP[j].getF() + "";
                String col = vectorP[j].getC() + "";
                String ruta = "src/IMG/" + vectorP[j].getNombre() + ".png";
                mostrarpoke(fi, col, ruta, 1);
            }
            sw = true;
            btn_mostrarcampo.setEnabled(false);
        }

        cambiaradefault(5000);
    }//GEN-LAST:event_btn_mostrarcampoActionPerformed

    private void btn_posicionarjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_posicionarjugadorActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ingresar tu posición de Juego Fila y Columna");
        String fil = "", col = "";
        fil = JOptionPane.showInputDialog("Posicion Fila: ");
        col = JOptionPane.showInputDialog("Posicion Columna: ");
        String ruta = "src/IMG/jugagor.png";
        mostrarpoke(fil, col, ruta, 22);
        cambiaradefault(8000);
        int f = Integer.parseInt(fil);
        int c = Integer.parseInt(col);
        if (fil.equalsIgnoreCase("1") && col.equalsIgnoreCase("1")) {

            buscarimg(f, c + 1);
            buscarimg(f + 1, c + 1);
            buscarimg(f + 1, c);

        } else if (fil.equalsIgnoreCase("6") && col.equalsIgnoreCase("1")) {
            buscarimg(f, c + 1);
            buscarimg(f - 1, c + 1);
            buscarimg(f - 1, c);
        } else if (fil.equalsIgnoreCase("1") && col.equalsIgnoreCase("6")) {
            buscarimg(f, c - 1);
            buscarimg(f + 1, c - 1);
            buscarimg(f + 1, c);
        } else if (fil.equalsIgnoreCase("6") && col.equalsIgnoreCase("6")) {
            buscarimg(f - 1, c);
            buscarimg(f - 1, c - 1);
            buscarimg(f, c - 1);
        } else {

            buscarimg(f, c + 1);
            buscarimg(f + 1, c + 1);
            buscarimg(f + 1, c);

            buscarimg(f - 1, c);
            buscarimg(f - 1, c - 1);
            buscarimg(f, c - 1);

            buscarimg(f - 1, c + 1);

            buscarimg(f + 1, c - 1);

        }


    }//GEN-LAST:event_btn_posicionarjugadorActionPerformed

    private void btn_crear_pokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_pokemonActionPerformed
        // TODO add your handling code here:
        if (i <= 5) {
            new crear_Pk().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "¡CAMPO DE JUEGO LLENO! \n NO PUEDE INGRESAR MAS POKEMONES.", "LO SENTIMOS",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btn_crear_pokemonActionPerformed

    private void btn_agarrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agarrarActionPerformed
        int fil, col;
        fil = Integer.parseInt(JOptionPane.showInputDialog("INGRESE FILA DE POKEMON A CAPTURAR: "));
        col = Integer.parseInt(JOptionPane.showInputDialog("INGRESE COLUMNA DE POKEMON A CAPTURAR"));
        String f, c;
        String ruta = "src/IMG/pokebola.png";
        int e = 0;
        for (int a = 0; a < i; a++) {
            if (vectorP[a].getF() == fil && vectorP[a].getC() == col) {

                pokebola.add(vectorP[a]);
                // JOptionPane.showMessageDialog(null, "es: "+p.getNombre());
                mostrarpoke(fil + "", col + "", ruta, 000);
                eliminarenv(a);
                e = 1;
            }

        }
        if (e == 0) {

            JOptionPane.showMessageDialog(null, "NO SE ENCONTRÓ POKEMON EN LA POSICION INDICADA o REVISE LOS DATOS INGRESADOS. ", "LO SENTIMOS",
                    JOptionPane.WARNING_MESSAGE);

        }

        cambiaradefault(3000);

    }//GEN-LAST:event_btn_agarrarActionPerformed

    private void btn_mostrarpokebolsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarpokebolsaActionPerformed

        if (pokebola.size() == 0) {
            JOptionPane.showMessageDialog(null, "POKEBOLA VACIA");
        } else {
            for (int j = 0; j < pokebola.size(); j++) {
                
                JOptionPane.showMessageDialog(null, pokebola.get(j).getNombre());
//            for (pokemon p1 : pokebola) {
//                JOptionPane.showMessageDialog(null, p1.getNombre());
            }
        }

//        for (int j = 0; j < pokebola.size(); j++) {
//            JOptionPane.showMessageDialog(null, pokebola.get(j).getNombre());
//        }

    }//GEN-LAST:event_btn_mostrarpokebolsaActionPerformed

    private void btn_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reiniciarActionPerformed
        i = 0;
        sw = true;
        btn_mostrarcampo.setEnabled(true);
        p = null;
    }//GEN-LAST:event_btn_reiniciarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed

        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "GRACIAS POR HABER JUGADO!");
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    // CAMBIAR LA IMAGEN PASANDO EL LABEL NAME Y ROOT
    private void setImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();

    }

    private void eliminarenv(int pos) {
        for (int j = pos; j < i; j++) {
            vectorP[j] = vectorP[j + 1];
        }
        i--;
    }

    public void buscarimg(int fil, int col) {
        String ruta = "";
        for (int a = 0; a < i; a++) {
            if (vectorP[a].getF() == fil && vectorP[a].getC() == col) {
                ruta = "src/IMG/" + vectorP[a].getNombre() + ".png";

                mostrarpoke(fil + "", col + "", ruta, 33);
                //JOptionPane.showMessageDialog(null, "ENTRO: " + vectorP[a].getNombre()+"  "+fil+""+" , "+col+"  " +ruta);

            }
        }
        cambiaradefault(5000);

    }

    public void cambiaradefault(int vel) {
        Timer timer;
        TimerTask tarea;
        tarea = new TimerTask() {
            @Override
            public void run() {

                for (int j = 1; j < 7; j++) {
                    for (int k = 1; k < 7; k++) {
                        mostrarpoke(j + "", k + "", "src/IMG/DEFAULT.png", 0);

                    }

                }

            }

        };

        timer = new Timer();
        timer.schedule(tarea, vel);

    }

    public void mostrarpoke(String fil, String col, String ruta, int tipom) {
        switch (fil) {
            case "1":
                if (null != col) {
                    switch (col) {
                        case "1" ->
                            setImageLabel(label_11, ruta);
                        case "2" ->
                            setImageLabel(label_12, ruta);
                        case "3" ->
                            setImageLabel(label_13, ruta);
                        case "4" ->
                            setImageLabel(label_14, ruta);
                        case "5" ->
                            setImageLabel(label_15, ruta);
                        case "6" ->
                            setImageLabel(label_16, ruta);
                        default -> {
                            if (tipom == 22) {
                                JOptionPane.showMessageDialog(null, "Ubicacion Errada Coordenadas no Existen");
                            }

                        }
                    }
                }
                break;
            case "2":
                if (null != col) {
                    switch (col) {
                        case "1" ->
                            setImageLabel(label_21, ruta);
                        case "2" ->
                            setImageLabel(label_22, ruta);
                        case "3" ->
                            setImageLabel(label_23, ruta);
                        case "4" ->
                            setImageLabel(label_24, ruta);
                        case "5" ->
                            setImageLabel(label_25, ruta);
                        case "6" ->
                            setImageLabel(label_26, ruta);
                        default -> {
                            if (tipom == 22) {
                                JOptionPane.showMessageDialog(null, "Ubicacion Errada Coordenadas no Existen");
                            }
                        }
                    }
                }
                break;
            case "3":
                if (null != col) {
                    switch (col) {
                        case "1" ->
                            setImageLabel(label_31, ruta);
                        case "2" ->
                            setImageLabel(label_32, ruta);
                        case "3" ->
                            setImageLabel(label_33, ruta);
                        case "4" ->
                            setImageLabel(label_34, ruta);
                        case "5" ->
                            setImageLabel(label_35, ruta);
                        case "6" ->
                            setImageLabel(label_36, ruta);
                        default -> {
                            if (tipom == 22) {
                                JOptionPane.showMessageDialog(null, "Ubicacion Errada Coordenadas no Existen");
                            }
                        }
                    }
                }
                break;

            case "4":
                if (null != col) {
                    switch (col) {
                        case "1" ->
                            setImageLabel(label_41, ruta);
                        case "2" ->
                            setImageLabel(label_42, ruta);
                        case "3" ->
                            setImageLabel(label_43, ruta);
                        case "4" ->
                            setImageLabel(label_44, ruta);
                        case "5" ->
                            setImageLabel(label_45, ruta);
                        case "6" ->
                            setImageLabel(label_46, ruta);
                        default -> {
                            if (tipom == 22) {
                                JOptionPane.showMessageDialog(null, "Ubicacion Errada Coordenadas no Existen");
                            }
                        }
                    }
                }
                break;

            case "5":
                if (null != col) {
                    switch (col) {
                        case "1" ->
                            setImageLabel(label_51, ruta);
                        case "2" ->
                            setImageLabel(label_52, ruta);
                        case "3" ->
                            setImageLabel(label_53, ruta);
                        case "4" ->
                            setImageLabel(label_54, ruta);
                        case "5" ->
                            setImageLabel(label_55, ruta);
                        case "6" ->
                            setImageLabel(label_56, ruta);
                        default -> {
                            if (tipom == 22) {
                                JOptionPane.showMessageDialog(null, "Ubicacion Errada Coordenadas no Existen");
                            }
                        }
                    }
                }
                break;

            case "6":
                if (null != col) {
                    switch (col) {
                        case "1" ->
                            setImageLabel(label_61, ruta);
                        case "2" ->
                            setImageLabel(label_62, ruta);
                        case "3" ->
                            setImageLabel(label_63, ruta);
                        case "4" ->
                            setImageLabel(label_64, ruta);
                        case "5" ->
                            setImageLabel(label_65, ruta);
                        case "6" ->
                            setImageLabel(label_66, ruta);
                        default -> {
                            if (tipom == 22) {
                                JOptionPane.showMessageDialog(null, "Ubicacion Errada Coordenadas no Existen");
                            }
                        }
                    }
                }
                break;
            default:
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPANEL_FONDO;
    private javax.swing.JButton btn_agarrar;
    private javax.swing.JButton btn_crear_pokemon;
    private javax.swing.JButton btn_mostrarcampo;
    private javax.swing.JButton btn_mostrarpokebolsa;
    private javax.swing.JButton btn_posicionarjugador;
    private javax.swing.JButton btn_reiniciar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_11;
    private javax.swing.JLabel label_12;
    private javax.swing.JLabel label_13;
    private javax.swing.JLabel label_14;
    private javax.swing.JLabel label_15;
    private javax.swing.JLabel label_16;
    private javax.swing.JLabel label_21;
    private javax.swing.JLabel label_22;
    private javax.swing.JLabel label_23;
    private javax.swing.JLabel label_24;
    private javax.swing.JLabel label_25;
    private javax.swing.JLabel label_26;
    private javax.swing.JLabel label_31;
    private javax.swing.JLabel label_32;
    private javax.swing.JLabel label_33;
    private javax.swing.JLabel label_34;
    private javax.swing.JLabel label_35;
    private javax.swing.JLabel label_36;
    private javax.swing.JLabel label_41;
    private javax.swing.JLabel label_42;
    private javax.swing.JLabel label_43;
    private javax.swing.JLabel label_44;
    private javax.swing.JLabel label_45;
    private javax.swing.JLabel label_46;
    private javax.swing.JLabel label_51;
    private javax.swing.JLabel label_52;
    private javax.swing.JLabel label_53;
    private javax.swing.JLabel label_54;
    private javax.swing.JLabel label_55;
    private javax.swing.JLabel label_56;
    private javax.swing.JLabel label_61;
    private javax.swing.JLabel label_62;
    private javax.swing.JLabel label_63;
    private javax.swing.JLabel label_64;
    private javax.swing.JLabel label_65;
    private javax.swing.JLabel label_66;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JButton mostrar_vectorP;
    // End of variables declaration//GEN-END:variables

}
